// lib/core/localization/ar.dart
const Map<String, String> ar = {
  'appName': 'المنزل الذكي',
  'dashboard': 'لوحة التحكم',
  'devices': 'الأجهزة',
  'analytics': 'التحليلات',
  'energySaving': 'توفير الطاقة',
  'settings': 'الإعدادات',
  'voltage': 'الجهد الكهربائي',
  'current': 'التيار الكهربائي',
  'power': 'الطاقة',
  'totalConsumption': 'إجمالي الاستهلاك',
  'activeDevices': 'الأجهزة النشطة',
  'totalLoad': 'إجمالي الحمل',
  'onTimeToday': 'مدة التشغيل اليوم',
  'costToday': 'تكلفة اليوم',
  'billPrediction': 'توقعات الفاتورة الشهرية',
  'autoMode': 'توفير الطاقة التلقائي',
  'priority': 'أولوية الجهاز',
  'language': 'اللغة',
  'theme': 'المظهر',
  'mqttConfig': 'إعدادات MQTT',
  'notifications': 'الإشعارات',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'search': 'بحث',
  'add': 'إضافة',
  'delete': 'حذف',
  'edit': 'تعديل',
};
