// lib/core/localization/en.dart
const Map<String, String> en = {
  'appName': 'Smart Home',
  'dashboard': 'Dashboard',
  'devices': 'Devices',
  'analytics': 'Analytics',
  'energySaving': 'Energy Saving',
  'settings': 'Settings',
  'voltage': 'Voltage',
  'current': 'Current',
  'power': 'Power',
  'totalConsumption': 'Total Consumption',
  'activeDevices': 'Active Devices',
  'totalLoad': 'Total Load',
  'onTimeToday': 'On Time Today',
  'costToday': 'Cost Today',
  'billPrediction': 'Monthly Bill Prediction',
  'autoMode': 'Auto Energy Saving',
  'priority': 'Device Priority',
  'language': 'Language',
  'theme': 'Theme',
  'mqttConfig': 'MQTT Configuration',
  'notifications': 'Notifications',
  'save': 'Save',
  'cancel': 'Cancel',
  'search': 'Search',
  'add': 'Add',
  'delete': 'Delete',
  'edit': 'Edit',
};
